CREATE TABLE USUARIO(
	IDUSUARIO		UNIQUEIDENTIFIER	NOT NULL,
	NOME			NVARCHAR(150)		NOT NULL,
	EMAIL			NVARCHAR(100)		NOT NULL UNIQUE,
	SENHA			NVARCHAR(50)		NOT NULL,
	DATAINCLUSAO	DATETIME			NOT NULL,
	PRIMEIROACESSO	INTEGER				NOT NULL,
	PRIMARY KEY(IDUSUARIO),
	CHECK(PRIMEIROACESSO IN(0,1)))
GO

CREATE TABLE EVENTO(
	IDEVENTO		UNIQUEIDENTIFIER	NOT NULL,
	NOME			NVARCHAR(250)		NOT NULL,
	DATA			DATE				NOT NULL,
	HORA			TIME				NOT NULL,
	PRIORIDADE		INTEGER				NOT NULL,
	DESCRICAO		NVARCHAR(500)		NOT NULL,
	ATIVO			INTEGER				NOT NULL,
	IDUSUARIO		UNIQUEIDENTIFIER	NOT NULL,
	PRIMARY KEY(IDEVENTO),
	FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(IDUSUARIO),
	CHECK(PRIORIDADE IN(0,1,2)),
	CHECK(ATIVO IN(0,1)))
GO


